name: feature

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: unit-tests
        run: ./gradlew testDebugUnitTest

  unit-test-by-impact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: fetch_dev
        run: git fetch origin dev:dev
      - name: clean
        run: ./gradlew clean
      - name: unit-tests
        run: ./gradlew runAffectedUnitTests -Paffected_module_detector.enable
      - name: show-log
        run: cat /home/runner/work/AMDTest/AMDTest/tools/impact-analysis/output/affected_module_detector.log

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
