name: feature

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  unit-test-by-impact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: fetch_dev
        run: git fetch origin dev:dev
      - name: unit-tests
        run: ./gradlew runAffectedUnitTests -Paffected_module_detector.enable

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
