name: feature

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build with Gradle
      run: ./gradlew build
